# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
