# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20190107_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
